---
- name: Copy keys to Kea configuration directory
  ansible.builtin.include_tasks: key_management.yml
  when: kea_ddns_enabled

- name: "Copy Kea DHCP{{ outer_item.dhcp_ip_version }} configuration files"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ kea_container_base_dir }}/config/{{ item | regex_replace('.j2', '') }}"
    owner: "root"
    group: "101"
    mode: "0664"
  loop:
    - "dhcp{{ outer_item.dhcp_ip_version }}.json.j2"
    - "subnet{{ outer_item.dhcp_ip_version }}.json.j2"
  register: kea_config

- name: "Pull Kea DHCP{{ outer_item.dhcp_ip_version }} image"
  community.docker.docker_image:
    name: "{{ outer_item.container_image }}"
    source: pull
    force_source: false
  register: kea_image_pull
  retries: 3
  delay: 15
  until: kea_image_pull is not failed

- name: "Start Kea DHCP{{ outer_item.dhcp_ip_version }} container"
  community.docker.docker_container:
    name: "{{ outer_item.container_name }}"
    image: "{{ outer_item.container_image }}"
    pull: missing
    state: started
    restart_policy: unless-stopped
    command: "{{ outer_item.container_command }}"
    volumes:
      - "{{ kea_container_base_dir }}/config:/kea/config:ro"
      - "{{ kea_container_base_dir }}/leases:/kea/leases"
      - "{{ kea_container_base_dir }}/logs:/kea/logs"
      - "{{ kea_container_base_dir }}/sockets:/kea/sockets"
      - "{{ kea_container_base_dir }}/entrypoint.d:/entrypoint.d:ro"
    comparisons:
      networks: strict
    network_mode: host

- name: "Reload Kea DHCP{{ outer_item.dhcp_ip_version }} configuration"
  ansible.builtin.command: "docker kill --signal=HUP {{ outer_item.container_name }}"
  changed_when: true
  when: kea_config.changed
  notify: Reload Kea Control Agent
